### ISSUE TITLE
Fails all tests on schwab-api.oauth2.refreshExpiration

### ISSUE THREAD

**Issue by higgsja** [gporter0205/schwab-client-example#6]
gPorter does not appear to respond to issues but in case others are having issues.

On every test, I get the error:
com.pangility.schwab.api.client.unittest.SchwabMarketDataApiTest.optionQuoteNotFoundTest -- Time elapsed: 0.918 s <<< ERROR!
java.time.format.DateTimeParseException: Text '${schwab-api.oauth2.refreshExpiration}' could not be parsed at index 0

I do not see where this variable is set.

**Comment by gporter0205** [comment]
sorry, I don't look at this project often.  This is just the project with example code.  I try to respond to all issues in the schwab-api-client project on github though.  Would you mind posting your question over there so my response is documented for anyone else who would like info on the problem?  Thanks
